# Generated by Django 5.0.6 on 2024-06-15 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_problema', models.TextField()),
                ('tipo_servicio', models.CharField(choices=[('desarrollo', 'Desarrollo'), ('servicio_tecnico', 'Servicio Técnico'), ('consultoria_ti', 'Consultoría TI')], max_length=50)),
                ('urgencia_servicio', models.CharField(choices=[('alta', 'Prioridad Alta'), ('media', 'Prioridad Media'), ('baja', 'Prioridad Baja')], max_length=20)),
                ('plazo_deseado', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.perfilcliente')),
            ],
        ),
    ]
